### ISSUE TITLE
unknown tag !<!lambda> 

### ISSUE THREAD

**Issue by den3537** [rjmurph2241/baseboard-heating-thermostat#1]
gives this error  unknown tag !<!lambda> at line 44, column 69:  ... m).target_temperature_low * 18;"
home assistant
 core-2021.10.6
supervisor-2021.10.0
how can i fix it?

**Comment by rjmurph2241** [comment]
I'm able to successfully install it on an ESP8266.  Can you give some more context about when/how you get the error?

**Comment by den3537** [comment]
![2](https://user-images.githubusercontent.com/70741349/139455554-9a2e9d28-c033-4946-b485-a44120c098cb.png)

**Comment by rjmurph2241** [comment]
It looks like you are using the Home Assistant file editor.  You should be doing everything through the ESPHome interface.  Create a new device there then copy the code into the new device.

**Comment by den3537** [comment]
Thanks. works
